spring:
  profiles:
    active: local # 여기서 기본 활성화 profile 선택
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: 123
    driver-class-name: org.mariadb.jdbc.Driver # 드라이버 클래스 추가
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 테이블 자동 생성/업데이트 (개발용)
  logging:
    level:
      root: debug
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://dev-server:3306/dev_db
    username: devuser
    password: devpass
  jpa:
    show-sql: true
  logging:
    level:
      root: info
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mariadb://prod-server:3306/prod_db
    username: produser
    password: prodpass
  jpa:
    show-sql: false
  logging:
    level:
      root: warn
